Heat-Map
martinnajjar12/heat-map-smashing-magazine pull request #1
Opened 2020-08-26 21:05 UTC by martinnajjar12

### This is a heat-map for the Smashing Magazine:

We've built this page with:
- HTML5
- CSS3: Styling and Positioning.

2020-08-26 21:49 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

#### Hello Team :raised_hands: 

You did a splendid job on this project. The design looks quite good, and the code is very organized and clean :clap: 

However, there are two minor details that we need to fix in order to move forward:

- [ ] The layout looks different. On 1440px it has 2 rows of articles with 3 columns, and then the 3 rows of 3 columns each. In yours is different. As stated here:
https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/pageLayoutScreenSize.png

 _If it shows different in your screen for some reason (in this screen size), kindly send a print screen for the next review._

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91360253-76c22100-e7cc-11ea-9e51-b04790b9ba45.png) | ![image](https://user-images.githubusercontent.com/61479648/91360307-99ecd080-e7cc-11ea-85b7-3c51bec497c7.png) |

:arrow_up: 
Those print screens were took with 1440 px size

- [x] You should wrap all the articles in articles tags (check the inline comments for more)

#### As stated above, the project looks really good.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-26 21:49 UTC, expjazz commented on index.html
> +          </div>
- [ ] This is the main reason the project was not approved. All the articles should be covered by article tags.

![image](https://user-images.githubusercontent.com/61479648/91359603-4037d680-e7cb-11ea-82af-898ebdbadcf5.png)

2020-08-26 23:11 UTC, Spayco approved these changes
# Project Approved ✔️ 

really awesome job! this is one of the best if not the best work I've seen in this project! Good Work 🎉 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-27 14:40 UTC, martinnajjar12 commented
> # Project Approved ✔️
> really awesome job! this is one of the best if not the best work I've seen in this project! Good Work 🎉
> 
> thank you for making the required changes, your project is now approved!
> 
> ### please don't forget to merge to master, good luck with the next projects!
> Best,
> Aziz Mejri
> _contact me on [twitter](https://twitter.com/iSpaYco) or slack (@Spayco) if you need any help_

Thank You for the nice words and feedback!!

2020-08-27 14:40 UTC, merged